#!/bin/bash

CF=config
CFG=config_g
CFS=config_s
OK="OK"
FIRST="school"
SECOND="remote_git"
COMMENT="progress"

git status
git add *

if [ "$#" -gt 0 ]
then
	git commit -m "$1"
else
	git commit -m "${COMMENT}"
fi
echo "----------------------------------------------------------------"
echo "push to ${FIRST} git"
git push
if [ -a $CF ]
	then
		mv .git/$CF .git/$CFS
	else
		echo "${CF} file not found"
		OK="BAD"
fi
if [ -a $CFG ]
	then
		mv .git/$CFG .git/$CF
	else
		echo "${CFG} file not found"
		OK="BAD"
fi
echo "----------------------------------------------------------------${OK} (${FIRST} git)"
echo "push to ${SECOND} git"
git push
mv .git/$CF .git/$CFG
mv .git/$CFS .git/$CF
echo "----------------------------------------------------------------${OK} (${SECOND} git)"
